/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ContactForm = IDL.Record({
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'getAllMessagesByEmail' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, ContactForm))],
      ['query'],
    ),
  'getAllMessagesByTimestamp' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, ContactForm))],
      ['query'],
    ),
  'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ContactForm = IDL.Record({
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'getAllMessagesByEmail' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, ContactForm))],
        ['query'],
      ),
    'getAllMessagesByTimestamp' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, ContactForm))],
        ['query'],
      ),
    'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };